- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: us-east-2
      instance_type: t2.micro
      ami: ami-0b500ef59d8335eee  # Redhat
      keypair: awsdemo1 # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         aws_access_key: "AKIAINO2RDTT25YE6TAQ"  #from csv
         aws_secret_key: "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"
         group: SG1  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: "Demo"
         instance_tags:
            Name: "Demo"
         vpc_subnet_id: "subnet-8d1579f7"
         assign_public_ip: yes
      register: ec2
    - debug: var=ec2
